name: Update readme and feed.opml

on:
  workflow_dispatch:
  push:
    paths: 
      - 'podcasts.csv'
      - 'myformatter.py'
      - 'opml_generator.py'
      - '.github/workflows/updateInfo.yml'
  schedule:
    - cron:  '0 11 * * MON'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v3.2.0
      with:
        node-version: 16.x
    - name: Set up Python 3.10
      uses: actions/setup-python@v3.1.2
      with:
        python-version: 3.10
    - name: myformatter
      run: |
        python myformatter.py
    - name: update readme
      run: |
        python createTable.py
    - name: Generate feed.opml
      run: |
        python opml_generator.py
    - name: Commit files
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "update README and feed.opml after adding podcast(s)"
    - name: Push changes
      uses: ad-m/github-push-action@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}